### ISSUE TITLE
zone setup

### ISSUE THREAD

**Issue by xjustbmw** [Ken98045/On-Guard#11]
is there any way to setup zones other than rectangles?
or maybe combine more rectangles for only one zone ?

**Comment by Ken98045** [comment]
Not now.  You can obviously create as many as you like.  You should be able to approximate the area you are interested in.  

 

I don’t know if this will be added in the future.  There have been a couple of requests for this.  However, this would make things much more complex to implement.  In particular, one of the features that has long been planned is to determine the direction of movement (to/from an area focus point).   This would add significantly  to the complexity of that determination.

 

Right now I want to make sure that things are stable and generally useful.  There are a couple of other features that are planned.  Once those are done I’ll consider more complex features like this one.

**Comment by Ken98045** [comment]
This has been fixed/enhanced in version 3.0+.  You can now create any shape in a 64x64 grid on the picture.
