### ISSUE TITLE
Object reference not set to an instance (again?)

### ISSUE THREAD

**Issue by grannysmith59** [Ken98045/On-Guard#13]
v1.8.2.2

I seem to remember this happening a while back, and you fixed it.

Error appeared when clicking live image snapshot button, when no images existed for that camera.

![OnGuard](https://user-images.githubusercontent.com/53004856/108216142-0a482f00-712a-11eb-8eb1-cbf5288d36df.JPG)

**Comment by Ken98045** [comment]
There have been quite a few changes leading up to the 3.1.1 version.  While I can't guarantee that this issue won't occur again (this kind of error is very difficult to spot/correct unless I can see/duplicate the problem), there has been significant additional testing.   This specific error has been corrected.
