### ISSUE TITLE
v3.1.0 release files are the same as v3.0.1

### ISSUE THREAD

**Issue by fpstassi** [Ken98045/On-Guard#16]
The OnGuardSetup.zip for the v3.1.0 release is the same zip as the v3.0.1 release - same modified date, crc32, etc. I installed the v3.1.0 release and in OnGuard under Help -> About the version number is 3.0.0.

**Comment by Ken98045** [comment]
Sorry, things have been slow here so I got behind on the release/setup files.  They have now been updated with 3.1.1.  There were a few additional changes  with this release.
