### ISSUE TITLE
Unhandled Exception When Creating a New Area of Interest

### ISSUE THREAD

**Issue by tylergibson** [Ken98045/On-Guard#2]
When pressing F1 to create a new area of interest, I get an Unhandled Exception Dialog.  I have not been able to create any areas of interest.

System Information - 
Windows 10 Pro v 2004 (19041.630)
Intel Xeon E5-2687W v2 through Unraid KVM virtual machine
47.5gb of RAM (virtual)
Connecting through Remote Desktop (Client machine is also Windows 10 Pro)

Image resolution is 2560x1440 for camera processed images.

Any guidance on anything I've missed here? I'm currently running On-Guard Side by Side with the AiTool application and it seems to be working fine beyond areas of interest.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SAAI.Properties.Settings.get_EmailSetup() in C:\Users\Ken\Source\Repos\OnGuard\Properties\Settings.Designer.cs:line 78
   at SAAI.CreateAOI..ctor(Rectangle imageRect) in C:\Users\Ken\Source\Repos\OnGuard\CreateAOI.cs:line 21
   at SAAI.MainWindow.AcceptAreaOfInterest() in C:\Users\Ken\Source\Repos\OnGuard\MainWindow.cs:line 735
   at SAAI.MainWindow.OnKeyDown(Object sender, KeyEventArgs e) in C:\Users\Ken\Source\Repos\OnGuard\MainWindow.cs:line 716
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
On Guard
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/On%20Guard/On%20Guard/On%20Guard.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files%20(x86)/On%20Guard/On%20Guard/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Ken98045** [comment]
That is a new one.  I think it is related to the fact that you may not have setup your outgoing email server, but I can’t tell for sure.  It is basically checking to make sure that you have setup the email server before creating an area.   The reason of this is that the area definition is partially dependent on having email available even if you don’t plan on using email.  

 

I’ll check this today.   With any luck I should have a new version available today.  Unfortunately, I am in the middle of making some changes that aren’t fully implemented.   So, it may take a little while to get the fix up.

 

Can you tell me if you have an outgoing email server setup via Tools/Outgoing Email?

**Comment by tylergibson** [comment]
Aha, that was it!  Entering and confirming my mail settings resolves the issue.  Would definitely be good to decouple this if possible though :)

**Comment by Ken98045** [comment]
OK, I put a new release on GitHub.  This will be Version 1.1.3 found here: https://github.com/Ken98045/On-Guard/releases/tag/1.1.3   The release includes the source code, which you probably don’t need or want.  Just run the setup program.

 

FYI, the problem here appears to have included 2 parts.  First, you do need to setup an outgoing email server even if you have no plans to use it.  At some point I’ll get rid of that requirement, but for now please just go with it.  The second part was very strange.  In case you care I’ll give you the details.  The program is built using Visual Studio (Version 16.8).  Somehow that tool appears to have generated code that was not correct.  I was able to get around that.  Hopefully there won’t be any more time bombs like this one.

 

Thanks for giving this a try!  If you find any other bugs just do what you did.  The more information I have the better.  Since I don’t have a staff dedicated to finding bugs I need to do my best to find them, but rely on reports like this to smash the rest.

**Comment by tylergibson** [comment]
Thanks @Ken98045 - Looks to be problem solved.  Happy to help and will report back with any other bugs if I run across them :)
