### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by grannysmith59** [Ken98045/On-Guard#3]
Hi Ken, got this message this morning when clicking set notifications while editing areas of interest.

It seems to be looking for your user data folder.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SAAI.NotificationOptionsDialog..ctor(AreaOfInterest area) in C:\Users\Ken\Source\Repos\OnGuard\NotificationOptionsDialog.cs:line 34
   at SAAI.CreateAOI.NotificationsButton_Click(Object sender, EventArgs e) in C:\Users\Ken\Source\Repos\OnGuard\CreateAOI.cs:line 345
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
On Guard
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/On%20Guard/On%20Guard/On%20Guard.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files%20(x86)/On%20Guard/On%20Guard/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
MQTTnet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/On%20Guard/On%20Guard/MQTTnet.DLL
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by grannysmith59** [comment]
It's looking for your user folder!

**Comment by Ken98045** [comment]
As far as the user folder goes, this is just the location where the project is being built/put together.  This is just the default location that the Microsoft tool uses to place new projects.   It is just telling me where the specific problem is in the program.   However, it has nothing to do with looking on your machine for the that directory.    I will move it to keep it a little more private.  I appreciate you pointing it out to me.

 

As far as the problem you reported goes, it is very, very strange.  All the program  is attempting to do at that point in time is to highlight the Urls section on the windows that allows you to add/delete notification URLs.   Do you happen to recall whether or not you previously had any notification URLs for this area?   That shouldn’t make a difference, but it would be helpful to know.  

 

I did test this several times, and I can’t make that problem happen to me.  It may be (probably is) a unique combination of circumstances – the order in which things are done, the contents of the dialogs, etc..    Any other details on exactly what you were doing when it happened would be appreciated.

 

As far as correcting the problem goes, I suggest that you delete the area in question and then re-add it.  If it happens again, please respond to this email.  I will keep trying to see what the problem is.  Actually, if that fixes the problem please let me know that too.

**Comment by Ken98045** [comment]
I’ve done my best to figure out what is going on here.  So far I haven’t figured it out.  If you can’t get around the problem by deleting the area then please let me know.  I’ll keep looking at it.

**Comment by grannysmith59** [comment]
The problem doesn't exist anymore, it happened when I was setting it up for
the very first time, so there was no area set at the time, which is
probably why it happened.

On a seperate note, is there any way you can expose the mqtt payload, so
that the user can specify the format please?

I'm only monitoring for people, and don't need to know which area of
interest triggered it, personally I would like to set it as:

OnGuard/CameraName/Person

payload on and payload off

Thanks for your great work, I had AITool up and running, but didn't find it
particularly stable

Regards

Alan

**Comment by Ken98045** [comment]
I could probably setup a format such as OnGuard/{Camera}/{Area}/{Object} where if you leave the contents empty {} nothing would be added to the MQTT message.   I don’t know if anything else would be helpful as a part of that message format.

 

As far as the MQTT payload goes that is still in flux.  I personally don’t use MQTT, so I don’t know what would be most helpful.  I am considering setting up the payload as a JSON string with something like: Motion=”on”, FileName=”c:\BI\Data\Front1432556.jpg”,Confidence=”.9987”, imageData=”some very long base 64 data” .  There have been a couple of requests for something like this.

 

As far as the “payload on”, “payload off” goes, I think what you would like is some notification that motion has ceased.  I am working on this now.  What I think is going to happen is that (1) you specify the time to keep looking for activity on a per camera basis (not area) (2) with every picture that contains “interesting” activity (not in an ignore area, and maybe only in areas you’ve defined as interesting) the timer gets reset (3) once the timer triggers/runs out you will get an (optional) URL notification and an (optional) MQTT message.  I don’t think that we want to say motion is “off” on the first frame without interesting activity.   However, you could feel free to set the timer duration as 1 second if you want.

**Comment by grannysmith59** [comment]
Thanks very much, I look forward to seeing how things progress.

Alan

**Comment by Ken98045** [comment]
There have been a number of changes that deal with this and other issues.  Please re-open if you are still having problems.

**Comment by grannysmith59** [comment]
Thanks for implementing thos changes, are these buttons supposed to remain
green when enabled? (because they don't!)


[image: image.png]

Also a typo:

[image: image.png]

Thanks

Alan
